# Generated by Django 4.1.4 on 2022-12-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('estatura', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=30)),
                ('adoptado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('direccion_persona', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('descripcion_mascota', models.CharField(max_length=150)),
                ('nombre_dueno', models.CharField(max_length=20)),
                ('pets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypets.pets')),
            ],
            options={
                'verbose_name': 'Adoption',
                'ordering': ['id'],
            },
        ),
    ]
